# Generated by Django 4.0.8 on 2022-10-18 07:55

from django.db import migrations, models
import myapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_place_p_type_firebasedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='f_id',
            field=models.CharField(default=myapp.utils.create_new_ref_number, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_id',
            field=models.CharField(default=myapp.utils.create_new_ref_number, max_length=10, unique=True),
        ),
    ]
